//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PianoForte.Resourses.DatabaseStructure.MySqlTable {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Absences {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Absences() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PianoForte.Resourses.DatabaseStructure.MySqlTable.Absences", typeof(Absences).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to absence_end.
        /// </summary>
        internal static string ColumnAbsenceEnd {
            get {
                return ResourceManager.GetString("ColumnAbsenceEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to absence_id.
        /// </summary>
        internal static string ColumnAbsenceId {
            get {
                return ResourceManager.GetString("ColumnAbsenceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to absence_reason.
        /// </summary>
        internal static string ColumnAbsenceReason {
            get {
                return ResourceManager.GetString("ColumnAbsenceReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to absence_start.
        /// </summary>
        internal static string ColumnAbsenceStart {
            get {
                return ResourceManager.GetString("ColumnAbsenceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to absence_status.
        /// </summary>
        internal static string ColumnAbsenceStatus {
            get {
                return ResourceManager.GetString("ColumnAbsenceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requestor_id.
        /// </summary>
        internal static string ColumnRequestorId {
            get {
                return ResourceManager.GetString("ColumnRequestorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requestor_type.
        /// </summary>
        internal static string ColumnRequestorType {
            get {
                return ResourceManager.GetString("ColumnRequestorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to absences.
        /// </summary>
        internal static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
    }
}
