//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PianoForte.Resourses.DatabaseStructure.MySqlTable {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Courses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Courses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PianoForte.Resourses.DatabaseStructure.MySqlTable.Courses", typeof(Courses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to classroom_duration.
        /// </summary>
        internal static string ColumnClassroomDuration {
            get {
                return ResourceManager.GetString("ColumnClassroomDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course_category_id.
        /// </summary>
        internal static string ColumnCourseCategoryId {
            get {
                return ResourceManager.GetString("ColumnCourseCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course_fee.
        /// </summary>
        internal static string ColumnCourseFee {
            get {
                return ResourceManager.GetString("ColumnCourseFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course_id.
        /// </summary>
        internal static string ColumnCourseId {
            get {
                return ResourceManager.GetString("ColumnCourseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course_level.
        /// </summary>
        internal static string ColumnCourseLevel {
            get {
                return ResourceManager.GetString("ColumnCourseLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course_name.
        /// </summary>
        internal static string ColumnCourseName {
            get {
                return ResourceManager.GetString("ColumnCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course_status.
        /// </summary>
        internal static string ColumnCourseStatus {
            get {
                return ResourceManager.GetString("ColumnCourseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number_of_times.
        /// </summary>
        internal static string ColumnNumberOfTimes {
            get {
                return ResourceManager.GetString("ColumnNumberOfTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to student_per_classroom.
        /// </summary>
        internal static string ColumnStudentPerClassroom {
            get {
                return ResourceManager.GetString("ColumnStudentPerClassroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to courses.
        /// </summary>
        internal static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
    }
}
