//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PianoForte.Resourses.DatabaseStructure.MySqlTable {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalUsers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalUsers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PianoForte.Resourses.DatabaseStructure.MySqlTable.LocalUsers", typeof(LocalUsers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local_user_firstname.
        /// </summary>
        internal static string ColumnLocalUserFirstname {
            get {
                return ResourceManager.GetString("ColumnLocalUserFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local_user_id.
        /// </summary>
        internal static string ColumnLocalUserId {
            get {
                return ResourceManager.GetString("ColumnLocalUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local_user_lastname.
        /// </summary>
        internal static string ColumnLocalUserLastname {
            get {
                return ResourceManager.GetString("ColumnLocalUserLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local_user_nickname.
        /// </summary>
        internal static string ColumnLocalUserNickname {
            get {
                return ResourceManager.GetString("ColumnLocalUserNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local_user_role.
        /// </summary>
        internal static string ColumnLocalUserRole {
            get {
                return ResourceManager.GetString("ColumnLocalUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local_user_status.
        /// </summary>
        internal static string ColumnLocalUserStatus {
            get {
                return ResourceManager.GetString("ColumnLocalUserStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local_users.
        /// </summary>
        internal static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
    }
}
