//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PianoForte.Resourses.DatabaseStructure.MySqlTable {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PaymentDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PianoForte.Resourses.DatabaseStructure.MySqlTable.PaymentDetails", typeof(PaymentDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discount.
        /// </summary>
        internal static string ColumnDiscount {
            get {
                return ResourceManager.GetString("ColumnDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment_detail_id.
        /// </summary>
        internal static string ColumnPaymentDetailId {
            get {
                return ResourceManager.GetString("ColumnPaymentDetailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment_id.
        /// </summary>
        internal static string ColumnPaymentId {
            get {
                return ResourceManager.GetString("ColumnPaymentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product_id.
        /// </summary>
        internal static string ColumnProductId {
            get {
                return ResourceManager.GetString("ColumnProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product_name.
        /// </summary>
        internal static string ColumnProductName {
            get {
                return ResourceManager.GetString("ColumnProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quantity.
        /// </summary>
        internal static string ColumnProductQuantity {
            get {
                return ResourceManager.GetString("ColumnProductQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product_type.
        /// </summary>
        internal static string ColumnProductType {
            get {
                return ResourceManager.GetString("ColumnProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product_unit_price.
        /// </summary>
        internal static string ColumnProductUnitPrice {
            get {
                return ResourceManager.GetString("ColumnProductUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment_details.
        /// </summary>
        internal static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
    }
}
