//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PianoForte.Resourses.DatabaseStructure.MySqlTable {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StudentAddresses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StudentAddresses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PianoForte.Resourses.DatabaseStructure.MySqlTable.StudentAddresses", typeof(StudentAddresses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to building_name.
        /// </summary>
        internal static string ColumnBuildingName {
            get {
                return ResourceManager.GetString("ColumnBuildingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country.
        /// </summary>
        internal static string ColumnCountry {
            get {
                return ResourceManager.GetString("ColumnCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to district.
        /// </summary>
        internal static string ColumnDistrict {
            get {
                return ResourceManager.GetString("ColumnDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to postcode.
        /// </summary>
        internal static string ColumnPostcode {
            get {
                return ResourceManager.GetString("ColumnPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to province.
        /// </summary>
        internal static string ColumnProvince {
            get {
                return ResourceManager.GetString("ColumnProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street_address.
        /// </summary>
        internal static string ColumnStreetAddress {
            get {
                return ResourceManager.GetString("ColumnStreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to student_address_id.
        /// </summary>
        internal static string ColumnStudentAddressId {
            get {
                return ResourceManager.GetString("ColumnStudentAddressId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to student_id.
        /// </summary>
        internal static string ColumnStudentId {
            get {
                return ResourceManager.GetString("ColumnStudentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subdistrict.
        /// </summary>
        internal static string ColumnSubdistrict {
            get {
                return ResourceManager.GetString("ColumnSubdistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to student_addresses.
        /// </summary>
        internal static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
    }
}
