// This file was autogenerated by D:\GitHub\PianoForte\PianoForte\Web\App\libs\closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../js/app.js', ['PianoForte.App'], ['PianoForte.Controllers.Teachers.TeacherController', 'PianoForte.Controllers.Teachers.TeacherMainController', 'PianoForte.Controllers.Widgets.MyBox.MyBoxController', 'PianoForte.Controllers.Widgets.MyTabs.MyTabsController', 'PianoForte.Directives.Widgets.MyBox.MyBoxDirective', 'PianoForte.Directives.Widgets.MyTabs.MyPaneDirective', 'PianoForte.Directives.Widgets.MyTabs.MyTabsDirective', 'PianoForte.Enum', 'PianoForte.Services.Teachers.TeacherService', 'PianoForte.Utilities.EnumConverter']);
goog.addDependency('../../../js/controllers/teachers/TeacherController.js', ['PianoForte.Controllers.Teachers.TeacherController'], ['PianoForte.Enum', 'PianoForte.Services.Teachers.TeacherService', 'PianoForte.Utilities.EnumConverter']);
goog.addDependency('../../../js/controllers/teachers/TeacherMainController.js', ['PianoForte.Controllers.Teachers.TeacherMainController'], []);
goog.addDependency('../../../js/controllers/widgets/my-box/MyBoxController.js', ['PianoForte.Controllers.Widgets.MyBox.MyBoxController'], []);
goog.addDependency('../../../js/controllers/widgets/my-tabs/MyTabsController.js', ['PianoForte.Controllers.Widgets.MyTabs.MyTabsController'], []);
goog.addDependency('../../../js/directives/widgets/my-box/MyBoxDirective.js', ['PianoForte.Directives.Widgets.MyBox.MyBoxDirective'], []);
goog.addDependency('../../../js/directives/widgets/my-tabs/MyPaneDirective.js', ['PianoForte.Directives.Widgets.MyTabs.MyPaneDirective'], []);
goog.addDependency('../../../js/directives/widgets/my-tabs/MyTabsDirective.js', ['PianoForte.Directives.Widgets.MyTabs.MyTabsDirective'], []);
goog.addDependency('../../../js/enum.js', ['PianoForte.Enum'], []);
goog.addDependency('../../../js/services/teachers/TeacherService.js', ['PianoForte.Services.Teachers.TeacherService'], []);
goog.addDependency('../../../js/utilities/EnumConverter.js', ['PianoForte.Utilities.EnumConverter'], []);
