// This file was autogenerated by D:\GitHub\PianoForte\PianoForte\Web\App\libs\closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../js/app.js', ['PianoForte.App'], ['PianoForte.Controllers.Books.BookController', 'PianoForte.Controllers.Books.BookMainController', 'PianoForte.Controllers.Cds.CdController', 'PianoForte.Controllers.Cds.CdMainController', 'PianoForte.Controllers.Courses.CourseController', 'PianoForte.Controllers.Courses.CourseMainController', 'PianoForte.Controllers.Students.StudentController', 'PianoForte.Controllers.Students.StudentMainController', 'PianoForte.Controllers.Teachers.TeacherController', 'PianoForte.Controllers.Teachers.TeacherMainController', 'PianoForte.Controllers.Widgets.MyBox.MyBoxController', 'PianoForte.Controllers.Widgets.MyDialogBox.MyDialogBoxController', 'PianoForte.Controllers.Widgets.MyLeftMenu.MyLeftMenuController', 'PianoForte.Controllers.Widgets.MyTabs.MyTabsController', 'PianoForte.Directives.Widgets.MyBox.MyBoxDirective', 'PianoForte.Directives.Widgets.MyDialogBox.MyDialogBoxDirective', 'PianoForte.Directives.Widgets.MyLeftMenu.MyLeftMenuDirective', 'PianoForte.Directives.Widgets.MyTabs.MyPaneDirective', 'PianoForte.Directives.Widgets.MyTabs.MyTabsDirective', 'PianoForte.Enum', 'PianoForte.Services.Teachers.TeacherService', 'PianoForte.Utilities.EnumConverter']);
goog.addDependency('../../../js/controllers/books/BookController.js', ['PianoForte.Controllers.Books.BookController'], []);
goog.addDependency('../../../js/controllers/books/BookMainController.js', ['PianoForte.Controllers.Books.BookMainController'], []);
goog.addDependency('../../../js/controllers/cds/CdController.js', ['PianoForte.Controllers.Cds.CdController'], []);
goog.addDependency('../../../js/controllers/cds/CdMainController.js', ['PianoForte.Controllers.Cds.CdMainController'], []);
goog.addDependency('../../../js/controllers/courses/CourseController.js', ['PianoForte.Controllers.Courses.CourseController'], []);
goog.addDependency('../../../js/controllers/courses/CourseMainController.js', ['PianoForte.Controllers.Courses.CourseMainController'], []);
goog.addDependency('../../../js/controllers/students/StudentController.js', ['PianoForte.Controllers.Students.StudentController'], []);
goog.addDependency('../../../js/controllers/students/StudentMainController.js', ['PianoForte.Controllers.Students.StudentMainController'], []);
goog.addDependency('../../../js/controllers/teachers/TeacherController.js', ['PianoForte.Controllers.Teachers.TeacherController'], ['PianoForte.Enum', 'PianoForte.Services.Teachers.TeacherService', 'PianoForte.Utilities.EnumConverter']);
goog.addDependency('../../../js/controllers/teachers/TeacherMainController.js', ['PianoForte.Controllers.Teachers.TeacherMainController'], []);
goog.addDependency('../../../js/controllers/widgets/my-box/MyBoxController.js', ['PianoForte.Controllers.Widgets.MyBox.MyBoxController'], []);
goog.addDependency('../../../js/controllers/widgets/my-dialog-box/MyDialogBoxController.js', ['PianoForte.Controllers.Widgets.MyDialogBox.MyDialogBoxController'], []);
goog.addDependency('../../../js/controllers/widgets/my-left-menu/MyLeftMenuController.js', ['PianoForte.Controllers.Widgets.MyLeftMenu.MyLeftMenuController'], []);
goog.addDependency('../../../js/controllers/widgets/my-tabs/MyTabsController.js', ['PianoForte.Controllers.Widgets.MyTabs.MyTabsController'], []);
goog.addDependency('../../../js/directives/widgets/my-box/MyBoxDirective.js', ['PianoForte.Directives.Widgets.MyBox.MyBoxDirective'], []);
goog.addDependency('../../../js/directives/widgets/my-dialog-box/MyDialogBoxDirective.js', ['PianoForte.Directives.Widgets.MyDialogBox.MyDialogBoxDirective'], []);
goog.addDependency('../../../js/directives/widgets/my-left-menu/MyLeftMenuDirective.js', ['PianoForte.Directives.Widgets.MyLeftMenu.MyLeftMenuDirective'], []);
goog.addDependency('../../../js/directives/widgets/my-tabs/MyPaneDirective.js', ['PianoForte.Directives.Widgets.MyTabs.MyPaneDirective'], []);
goog.addDependency('../../../js/directives/widgets/my-tabs/MyTabsDirective.js', ['PianoForte.Directives.Widgets.MyTabs.MyTabsDirective'], []);
goog.addDependency('../../../js/enum.js', ['PianoForte.Enum'], []);
goog.addDependency('../../../js/services/teachers/TeacherService.js', ['PianoForte.Services.Teachers.TeacherService'], []);
goog.addDependency('../../../js/utilities/EnumConverter.js', ['PianoForte.Utilities.EnumConverter'], []);
